In [2]:
import numpy as np
list_ = ['1','2','3','4','5']

array_list = np.array(list_)
array_list

array(['1', '2', '3', '4', '5'], dtype='<U1')

#  Is there any difference in the data type of variables list_ and array_list? If there is then write a code to print the data types of both the variables


In [3]:
type(list_)

list

In [4]:
type(array_list)

numpy.ndarray

In [5]:
# The main difference is that NumPy arrays are much faster and have strict requirements on the homogeneity of the objects.
# For example, a NumPy array of strings can only contain strings and no other data types, but a Python list can contain a 
# mixture of strings, numbers, booleans and other objects.


In [6]:
array_list.ndim


1

#  Write a code to print the data type of each and every element of both the variables list_ and arra_list 


In [7]:
for i in list_:
    print(type(i))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>


In [11]:
array_list.dtype

dtype('<U1')

In [13]:
import pandas as pd
df = pd.DataFrame()
df["Element"] = array_list

In [17]:
df["DataType"]=df["Element"].apply(type)

In [18]:
df

Element       DataType
0       1  <class 'str'>
1       2  <class 'str'>
2       3  <class 'str'>
3       4  <class 'str'>
4       5  <class 'str'>

#  Considering the following changes in the variable, array_list: array_list = np.array(object = list_, dtype = int)



In [19]:
array_list = np.array(object= list_,dtype = int)

In [20]:
df = pd.DataFrame()
df["Element"] = array_list
df["DataType"]=df["Element"].apply(type)
df

Element       DataType
0        1  <class 'int'>
1        2  <class 'int'>
2        3  <class 'int'>
3        4  <class 'int'>
4        5  <class 'int'>

# Write a code to find the following characteristics of variable, num_array:           (i)	 shape (ii) size



In [22]:
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]

num_array = np.array(object = num_list)
num_array

array([[1, 2, 3],
       [4, 5, 6]])

In [23]:
num_array.shape

(2, 3)

In [24]:
num_array.size

6

#  Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array creation function.  [Hint: The size of the array will be 9 and the shape will be (3,3).]


In [25]:
array = np.zeros((3,3))
array

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

#  Create an identity matrix of shape (5,5) using numpy functions? [Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]



In [27]:
I = np.eye(5)
I

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])